import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import Subscribe from "./components/Subscribe";
import Scrolltotop from "./components/Scrolltotop";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Plants E-shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Subscribe />
        <Scrolltotop />
        <Footer />
        </body>
    </html>
  );
}
